// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace com.alicloud.openservices.tablestore.core.protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Error : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code", IsRequired = true)]
        public string Code { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get { return __pbn__Message ?? ""; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PrimaryKeySchema : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type", IsRequired = true)]
        public PrimaryKeyType Type { get; set; } = PrimaryKeyType.Integer;

        [global::ProtoBuf.ProtoMember(3, Name = @"option")]
        [global::System.ComponentModel.DefaultValue(PrimaryKeyOption.AutoIncrement)]
        public PrimaryKeyOption Option
        {
            get { return __pbn__Option ?? PrimaryKeyOption.AutoIncrement; }
            set { __pbn__Option = value; }
        }
        public bool ShouldSerializeOption() => __pbn__Option != null;
        public void ResetOption() => __pbn__Option = null;
        private PrimaryKeyOption? __pbn__Option;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PartitionRange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"begin", IsRequired = true)]
        public byte[] Begin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end", IsRequired = true)]
        public byte[] End { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time_to_live")]
        public int TimeToLive
        {
            get { return __pbn__TimeToLive.GetValueOrDefault(); }
            set { __pbn__TimeToLive = value; }
        }
        public bool ShouldSerializeTimeToLive() => __pbn__TimeToLive != null;
        public void ResetTimeToLive() => __pbn__TimeToLive = null;
        private int? __pbn__TimeToLive;

        [global::ProtoBuf.ProtoMember(2, Name = @"max_versions")]
        public int MaxVersions
        {
            get { return __pbn__MaxVersions.GetValueOrDefault(); }
            set { __pbn__MaxVersions = value; }
        }
        public bool ShouldSerializeMaxVersions() => __pbn__MaxVersions != null;
        public void ResetMaxVersions() => __pbn__MaxVersions = null;
        private int? __pbn__MaxVersions;

        [global::ProtoBuf.ProtoMember(3, Name = @"bloom_filter_type")]
        [global::System.ComponentModel.DefaultValue(BloomFilterType.None)]
        public BloomFilterType BloomFilterType
        {
            get { return __pbn__BloomFilterType ?? BloomFilterType.None; }
            set { __pbn__BloomFilterType = value; }
        }
        public bool ShouldSerializeBloomFilterType() => __pbn__BloomFilterType != null;
        public void ResetBloomFilterType() => __pbn__BloomFilterType = null;
        private BloomFilterType? __pbn__BloomFilterType;

        [global::ProtoBuf.ProtoMember(4, Name = @"block_size")]
        public int BlockSize
        {
            get { return __pbn__BlockSize.GetValueOrDefault(); }
            set { __pbn__BlockSize = value; }
        }
        public bool ShouldSerializeBlockSize() => __pbn__BlockSize != null;
        public void ResetBlockSize() => __pbn__BlockSize = null;
        private int? __pbn__BlockSize;

        [global::ProtoBuf.ProtoMember(5, Name = @"deviation_cell_version_in_sec")]
        public long DeviationCellVersionInSec
        {
            get { return __pbn__DeviationCellVersionInSec.GetValueOrDefault(); }
            set { __pbn__DeviationCellVersionInSec = value; }
        }
        public bool ShouldSerializeDeviationCellVersionInSec() => __pbn__DeviationCellVersionInSec != null;
        public void ResetDeviationCellVersionInSec() => __pbn__DeviationCellVersionInSec = null;
        private long? __pbn__DeviationCellVersionInSec;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableMeta : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"primary_key")]
        public global::System.Collections.Generic.List<PrimaryKeySchema> PrimaryKeys { get; } = new global::System.Collections.Generic.List<PrimaryKeySchema>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Condition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"row_existence", IsRequired = true)]
        public RowExistenceExpectation RowExistence { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"column_condition")]
        public byte[] ColumnCondition
        {
            get { return __pbn__ColumnCondition; }
            set { __pbn__ColumnCondition = value; }
        }
        public bool ShouldSerializeColumnCondition() => __pbn__ColumnCondition != null;
        public void ResetColumnCondition() => __pbn__ColumnCondition = null;
        private byte[] __pbn__ColumnCondition;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CapacityUnit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"read")]
        public int Read
        {
            get { return __pbn__Read.GetValueOrDefault(); }
            set { __pbn__Read = value; }
        }
        public bool ShouldSerializeRead() => __pbn__Read != null;
        public void ResetRead() => __pbn__Read = null;
        private int? __pbn__Read;

        [global::ProtoBuf.ProtoMember(2, Name = @"write")]
        public int Write
        {
            get { return __pbn__Write.GetValueOrDefault(); }
            set { __pbn__Write = value; }
        }
        public bool ShouldSerializeWrite() => __pbn__Write != null;
        public void ResetWrite() => __pbn__Write = null;
        private int? __pbn__Write;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReservedThroughputDetails : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"capacity_unit", IsRequired = true)]
        public CapacityUnit CapacityUnit { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last_increase_time", IsRequired = true)]
        public long LastIncreaseTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"last_decrease_time")]
        public long LastDecreaseTime
        {
            get { return __pbn__LastDecreaseTime.GetValueOrDefault(); }
            set { __pbn__LastDecreaseTime = value; }
        }
        public bool ShouldSerializeLastDecreaseTime() => __pbn__LastDecreaseTime != null;
        public void ResetLastDecreaseTime() => __pbn__LastDecreaseTime = null;
        private long? __pbn__LastDecreaseTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReservedThroughput : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"capacity_unit", IsRequired = true)]
        public CapacityUnit CapacityUnit { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsumedCapacity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"capacity_unit", IsRequired = true)]
        public CapacityUnit CapacityUnit { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamSpecification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"enable_stream", IsRequired = true)]
        public bool EnableStream { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"expiration_time")]
        public int ExpirationTime
        {
            get { return __pbn__ExpirationTime.GetValueOrDefault(); }
            set { __pbn__ExpirationTime = value; }
        }
        public bool ShouldSerializeExpirationTime() => __pbn__ExpirationTime != null;
        public void ResetExpirationTime() => __pbn__ExpirationTime = null;
        private int? __pbn__ExpirationTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamDetails : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"enable_stream", IsRequired = true)]
        public bool EnableStream { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"stream_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StreamId
        {
            get { return __pbn__StreamId ?? ""; }
            set { __pbn__StreamId = value; }
        }
        public bool ShouldSerializeStreamId() => __pbn__StreamId != null;
        public void ResetStreamId() => __pbn__StreamId = null;
        private string __pbn__StreamId;

        [global::ProtoBuf.ProtoMember(3, Name = @"expiration_time")]
        public int ExpirationTime
        {
            get { return __pbn__ExpirationTime.GetValueOrDefault(); }
            set { __pbn__ExpirationTime = value; }
        }
        public bool ShouldSerializeExpirationTime() => __pbn__ExpirationTime != null;
        public void ResetExpirationTime() => __pbn__ExpirationTime = null;
        private int? __pbn__ExpirationTime;

        [global::ProtoBuf.ProtoMember(4, Name = @"last_enable_time")]
        public long LastEnableTime
        {
            get { return __pbn__LastEnableTime.GetValueOrDefault(); }
            set { __pbn__LastEnableTime = value; }
        }
        public bool ShouldSerializeLastEnableTime() => __pbn__LastEnableTime != null;
        public void ResetLastEnableTime() => __pbn__LastEnableTime = null;
        private long? __pbn__LastEnableTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateTableRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_meta", IsRequired = true)]
        public TableMeta TableMeta { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reserved_throughput", IsRequired = true)]
        public ReservedThroughput ReservedThroughput { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"table_options")]
        public TableOptions TableOptions { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"partitions")]
        public global::System.Collections.Generic.List<PartitionRange> Partitions { get; } = new global::System.Collections.Generic.List<PartitionRange>();

        [global::ProtoBuf.ProtoMember(5, Name = @"stream_spec")]
        public StreamSpecification StreamSpec { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateTableResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateTableRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reserved_throughput")]
        public ReservedThroughput ReservedThroughput { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"table_options")]
        public TableOptions TableOptions { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"stream_spec")]
        public StreamSpecification StreamSpec { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateTableResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reserved_throughput_details", IsRequired = true)]
        public ReservedThroughputDetails ReservedThroughputDetails { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"table_options", IsRequired = true)]
        public TableOptions TableOptions { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"stream_details")]
        public StreamDetails StreamDetails { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DescribeTableRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DescribeTableResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_meta", IsRequired = true)]
        public TableMeta TableMeta { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reserved_throughput_details", IsRequired = true)]
        public ReservedThroughputDetails ReservedThroughputDetails { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"table_options", IsRequired = true)]
        public TableOptions TableOptions { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"table_status", IsRequired = true)]
        public TableStatus TableStatus { get; set; } = TableStatus.Active;

        [global::ProtoBuf.ProtoMember(5, Name = @"stream_details")]
        public StreamDetails StreamDetails { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"shard_splits")]
        public global::System.Collections.Generic.List<byte[]> ShardSplits { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListTableRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListTableResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_names")]
        public global::System.Collections.Generic.List<string> TableNames { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteTableRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteTableResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoadTableRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoadTableResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnloadTableRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnloadTableResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TimeRange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start_time")]
        public long StartTime
        {
            get { return __pbn__StartTime.GetValueOrDefault(); }
            set { __pbn__StartTime = value; }
        }
        public bool ShouldSerializeStartTime() => __pbn__StartTime != null;
        public void ResetStartTime() => __pbn__StartTime = null;
        private long? __pbn__StartTime;

        [global::ProtoBuf.ProtoMember(2, Name = @"end_time")]
        public long EndTime
        {
            get { return __pbn__EndTime.GetValueOrDefault(); }
            set { __pbn__EndTime = value; }
        }
        public bool ShouldSerializeEndTime() => __pbn__EndTime != null;
        public void ResetEndTime() => __pbn__EndTime = null;
        private long? __pbn__EndTime;

        [global::ProtoBuf.ProtoMember(3, Name = @"specific_time")]
        public long SpecificTime
        {
            get { return __pbn__SpecificTime.GetValueOrDefault(); }
            set { __pbn__SpecificTime = value; }
        }
        public bool ShouldSerializeSpecificTime() => __pbn__SpecificTime != null;
        public void ResetSpecificTime() => __pbn__SpecificTime = null;
        private long? __pbn__SpecificTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReturnContent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"return_type")]
        [global::System.ComponentModel.DefaultValue(ReturnType.RtNone)]
        public ReturnType ReturnType
        {
            get { return __pbn__ReturnType ?? ReturnType.RtNone; }
            set { __pbn__ReturnType = value; }
        }
        public bool ShouldSerializeReturnType() => __pbn__ReturnType != null;
        public void ResetReturnType() => __pbn__ReturnType = null;
        private ReturnType? __pbn__ReturnType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRowRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"primary_key", IsRequired = true)]
        public byte[] PrimaryKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"columns_to_get")]
        public global::System.Collections.Generic.List<string> ColumnsToGets { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, Name = @"time_range")]
        public TimeRange TimeRange { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"max_versions")]
        public int MaxVersions
        {
            get { return __pbn__MaxVersions.GetValueOrDefault(); }
            set { __pbn__MaxVersions = value; }
        }
        public bool ShouldSerializeMaxVersions() => __pbn__MaxVersions != null;
        public void ResetMaxVersions() => __pbn__MaxVersions = null;
        private int? __pbn__MaxVersions;

        [global::ProtoBuf.ProtoMember(6, Name = @"cache_blocks")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool CacheBlocks
        {
            get { return __pbn__CacheBlocks ?? true; }
            set { __pbn__CacheBlocks = value; }
        }
        public bool ShouldSerializeCacheBlocks() => __pbn__CacheBlocks != null;
        public void ResetCacheBlocks() => __pbn__CacheBlocks = null;
        private bool? __pbn__CacheBlocks;

        [global::ProtoBuf.ProtoMember(7, Name = @"filter")]
        public byte[] Filter
        {
            get { return __pbn__Filter; }
            set { __pbn__Filter = value; }
        }
        public bool ShouldSerializeFilter() => __pbn__Filter != null;
        public void ResetFilter() => __pbn__Filter = null;
        private byte[] __pbn__Filter;

        [global::ProtoBuf.ProtoMember(8, Name = @"start_column")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StartColumn
        {
            get { return __pbn__StartColumn ?? ""; }
            set { __pbn__StartColumn = value; }
        }
        public bool ShouldSerializeStartColumn() => __pbn__StartColumn != null;
        public void ResetStartColumn() => __pbn__StartColumn = null;
        private string __pbn__StartColumn;

        [global::ProtoBuf.ProtoMember(9, Name = @"end_column")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EndColumn
        {
            get { return __pbn__EndColumn ?? ""; }
            set { __pbn__EndColumn = value; }
        }
        public bool ShouldSerializeEndColumn() => __pbn__EndColumn != null;
        public void ResetEndColumn() => __pbn__EndColumn = null;
        private string __pbn__EndColumn;

        [global::ProtoBuf.ProtoMember(10, Name = @"token")]
        public byte[] Token
        {
            get { return __pbn__Token; }
            set { __pbn__Token = value; }
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private byte[] __pbn__Token;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"consumed", IsRequired = true)]
        public ConsumedCapacity Consumed { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"row", IsRequired = true)]
        public byte[] Row { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"next_token")]
        public byte[] NextToken
        {
            get { return __pbn__NextToken; }
            set { __pbn__NextToken = value; }
        }
        public bool ShouldSerializeNextToken() => __pbn__NextToken != null;
        public void ResetNextToken() => __pbn__NextToken = null;
        private byte[] __pbn__NextToken;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateRowRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"row_change", IsRequired = true)]
        public byte[] RowChange { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"condition", IsRequired = true)]
        public Condition Condition { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"return_content")]
        public ReturnContent ReturnContent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"consumed", IsRequired = true)]
        public ConsumedCapacity Consumed { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"row")]
        public byte[] Row
        {
            get { return __pbn__Row; }
            set { __pbn__Row = value; }
        }
        public bool ShouldSerializeRow() => __pbn__Row != null;
        public void ResetRow() => __pbn__Row = null;
        private byte[] __pbn__Row;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PutRowRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"row", IsRequired = true)]
        public byte[] Row { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"condition", IsRequired = true)]
        public Condition Condition { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"return_content")]
        public ReturnContent ReturnContent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PutRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"consumed", IsRequired = true)]
        public ConsumedCapacity Consumed { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"row")]
        public byte[] Row
        {
            get { return __pbn__Row; }
            set { __pbn__Row = value; }
        }
        public bool ShouldSerializeRow() => __pbn__Row != null;
        public void ResetRow() => __pbn__Row = null;
        private byte[] __pbn__Row;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteRowRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"primary_key", IsRequired = true)]
        public byte[] PrimaryKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"condition", IsRequired = true)]
        public Condition Condition { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"return_content")]
        public ReturnContent ReturnContent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"consumed", IsRequired = true)]
        public ConsumedCapacity Consumed { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"row")]
        public byte[] Row
        {
            get { return __pbn__Row; }
            set { __pbn__Row = value; }
        }
        public bool ShouldSerializeRow() => __pbn__Row != null;
        public void ResetRow() => __pbn__Row = null;
        private byte[] __pbn__Row;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableInBatchGetRowRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"primary_key")]
        public global::System.Collections.Generic.List<byte[]> PrimaryKeys { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(3, Name = @"token")]
        public global::System.Collections.Generic.List<byte[]> Tokens { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(4, Name = @"columns_to_get")]
        public global::System.Collections.Generic.List<string> ColumnsToGets { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(5, Name = @"time_range")]
        public TimeRange TimeRange { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"max_versions")]
        public int MaxVersions
        {
            get { return __pbn__MaxVersions.GetValueOrDefault(); }
            set { __pbn__MaxVersions = value; }
        }
        public bool ShouldSerializeMaxVersions() => __pbn__MaxVersions != null;
        public void ResetMaxVersions() => __pbn__MaxVersions = null;
        private int? __pbn__MaxVersions;

        [global::ProtoBuf.ProtoMember(7, Name = @"cache_blocks")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool CacheBlocks
        {
            get { return __pbn__CacheBlocks ?? true; }
            set { __pbn__CacheBlocks = value; }
        }
        public bool ShouldSerializeCacheBlocks() => __pbn__CacheBlocks != null;
        public void ResetCacheBlocks() => __pbn__CacheBlocks = null;
        private bool? __pbn__CacheBlocks;

        [global::ProtoBuf.ProtoMember(8, Name = @"filter")]
        public byte[] Filter
        {
            get { return __pbn__Filter; }
            set { __pbn__Filter = value; }
        }
        public bool ShouldSerializeFilter() => __pbn__Filter != null;
        public void ResetFilter() => __pbn__Filter = null;
        private byte[] __pbn__Filter;

        [global::ProtoBuf.ProtoMember(9, Name = @"start_column")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StartColumn
        {
            get { return __pbn__StartColumn ?? ""; }
            set { __pbn__StartColumn = value; }
        }
        public bool ShouldSerializeStartColumn() => __pbn__StartColumn != null;
        public void ResetStartColumn() => __pbn__StartColumn = null;
        private string __pbn__StartColumn;

        [global::ProtoBuf.ProtoMember(10, Name = @"end_column")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EndColumn
        {
            get { return __pbn__EndColumn ?? ""; }
            set { __pbn__EndColumn = value; }
        }
        public bool ShouldSerializeEndColumn() => __pbn__EndColumn != null;
        public void ResetEndColumn() => __pbn__EndColumn = null;
        private string __pbn__EndColumn;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BatchGetRowRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tables")]
        public global::System.Collections.Generic.List<TableInBatchGetRowRequest> Tables { get; } = new global::System.Collections.Generic.List<TableInBatchGetRowRequest>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RowInBatchGetRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_ok", IsRequired = true)]
        public bool IsOk { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"error")]
        public Error Error { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"consumed")]
        public ConsumedCapacity Consumed { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"row")]
        public byte[] Row
        {
            get { return __pbn__Row; }
            set { __pbn__Row = value; }
        }
        public bool ShouldSerializeRow() => __pbn__Row != null;
        public void ResetRow() => __pbn__Row = null;
        private byte[] __pbn__Row;

        [global::ProtoBuf.ProtoMember(5, Name = @"next_token")]
        public byte[] NextToken
        {
            get { return __pbn__NextToken; }
            set { __pbn__NextToken = value; }
        }
        public bool ShouldSerializeNextToken() => __pbn__NextToken != null;
        public void ResetNextToken() => __pbn__NextToken = null;
        private byte[] __pbn__NextToken;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableInBatchGetRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"rows")]
        public global::System.Collections.Generic.List<RowInBatchGetRowResponse> Rows { get; } = new global::System.Collections.Generic.List<RowInBatchGetRowResponse>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BatchGetRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tables")]
        public global::System.Collections.Generic.List<TableInBatchGetRowResponse> Tables { get; } = new global::System.Collections.Generic.List<TableInBatchGetRowResponse>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RowInBatchWriteRowRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public OperationType Type { get; set; } = OperationType.Put;

        [global::ProtoBuf.ProtoMember(2, Name = @"row_change", IsRequired = true)]
        public byte[] RowChange { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"condition", IsRequired = true)]
        public Condition Condition { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"return_content")]
        public ReturnContent ReturnContent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableInBatchWriteRowRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"rows")]
        public global::System.Collections.Generic.List<RowInBatchWriteRowRequest> Rows { get; } = new global::System.Collections.Generic.List<RowInBatchWriteRowRequest>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BatchWriteRowRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tables")]
        public global::System.Collections.Generic.List<TableInBatchWriteRowRequest> Tables { get; } = new global::System.Collections.Generic.List<TableInBatchWriteRowRequest>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RowInBatchWriteRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_ok", IsRequired = true)]
        public bool IsOk { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"error")]
        public Error Error { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"consumed")]
        public ConsumedCapacity Consumed { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"row")]
        public byte[] Row
        {
            get { return __pbn__Row; }
            set { __pbn__Row = value; }
        }
        public bool ShouldSerializeRow() => __pbn__Row != null;
        public void ResetRow() => __pbn__Row = null;
        private byte[] __pbn__Row;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableInBatchWriteRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"rows")]
        public global::System.Collections.Generic.List<RowInBatchWriteRowResponse> Rows { get; } = new global::System.Collections.Generic.List<RowInBatchWriteRowResponse>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BatchWriteRowResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tables")]
        public global::System.Collections.Generic.List<TableInBatchWriteRowResponse> Tables { get; } = new global::System.Collections.Generic.List<TableInBatchWriteRowResponse>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRangeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"direction", IsRequired = true)]
        public Direction Direction { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"columns_to_get")]
        public global::System.Collections.Generic.List<string> ColumnsToGets { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, Name = @"time_range")]
        public TimeRange TimeRange { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"max_versions")]
        public int MaxVersions
        {
            get { return __pbn__MaxVersions.GetValueOrDefault(); }
            set { __pbn__MaxVersions = value; }
        }
        public bool ShouldSerializeMaxVersions() => __pbn__MaxVersions != null;
        public void ResetMaxVersions() => __pbn__MaxVersions = null;
        private int? __pbn__MaxVersions;

        [global::ProtoBuf.ProtoMember(6, Name = @"limit")]
        public int Limit
        {
            get { return __pbn__Limit.GetValueOrDefault(); }
            set { __pbn__Limit = value; }
        }
        public bool ShouldSerializeLimit() => __pbn__Limit != null;
        public void ResetLimit() => __pbn__Limit = null;
        private int? __pbn__Limit;

        [global::ProtoBuf.ProtoMember(7, Name = @"inclusive_start_primary_key", IsRequired = true)]
        public byte[] InclusiveStartPrimaryKey { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"exclusive_end_primary_key", IsRequired = true)]
        public byte[] ExclusiveEndPrimaryKey { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"cache_blocks")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool CacheBlocks
        {
            get { return __pbn__CacheBlocks ?? true; }
            set { __pbn__CacheBlocks = value; }
        }
        public bool ShouldSerializeCacheBlocks() => __pbn__CacheBlocks != null;
        public void ResetCacheBlocks() => __pbn__CacheBlocks = null;
        private bool? __pbn__CacheBlocks;

        [global::ProtoBuf.ProtoMember(10, Name = @"filter")]
        public byte[] Filter
        {
            get { return __pbn__Filter; }
            set { __pbn__Filter = value; }
        }
        public bool ShouldSerializeFilter() => __pbn__Filter != null;
        public void ResetFilter() => __pbn__Filter = null;
        private byte[] __pbn__Filter;

        [global::ProtoBuf.ProtoMember(11, Name = @"start_column")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StartColumn
        {
            get { return __pbn__StartColumn ?? ""; }
            set { __pbn__StartColumn = value; }
        }
        public bool ShouldSerializeStartColumn() => __pbn__StartColumn != null;
        public void ResetStartColumn() => __pbn__StartColumn = null;
        private string __pbn__StartColumn;

        [global::ProtoBuf.ProtoMember(12, Name = @"end_column")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EndColumn
        {
            get { return __pbn__EndColumn ?? ""; }
            set { __pbn__EndColumn = value; }
        }
        public bool ShouldSerializeEndColumn() => __pbn__EndColumn != null;
        public void ResetEndColumn() => __pbn__EndColumn = null;
        private string __pbn__EndColumn;

        [global::ProtoBuf.ProtoMember(13, Name = @"token")]
        public byte[] Token
        {
            get { return __pbn__Token; }
            set { __pbn__Token = value; }
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private byte[] __pbn__Token;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRangeResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"consumed", IsRequired = true)]
        public ConsumedCapacity Consumed { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"rows", IsRequired = true)]
        public byte[] Rows { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"next_start_primary_key")]
        public byte[] NextStartPrimaryKey
        {
            get { return __pbn__NextStartPrimaryKey; }
            set { __pbn__NextStartPrimaryKey = value; }
        }
        public bool ShouldSerializeNextStartPrimaryKey() => __pbn__NextStartPrimaryKey != null;
        public void ResetNextStartPrimaryKey() => __pbn__NextStartPrimaryKey = null;
        private byte[] __pbn__NextStartPrimaryKey;

        [global::ProtoBuf.ProtoMember(4, Name = @"next_token")]
        public byte[] NextToken
        {
            get { return __pbn__NextToken; }
            set { __pbn__NextToken = value; }
        }
        public bool ShouldSerializeNextToken() => __pbn__NextToken != null;
        public void ResetNextToken() => __pbn__NextToken = null;
        private byte[] __pbn__NextToken;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListStreamRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TableName
        {
            get { return __pbn__TableName ?? ""; }
            set { __pbn__TableName = value; }
        }
        public bool ShouldSerializeTableName() => __pbn__TableName != null;
        public void ResetTableName() => __pbn__TableName = null;
        private string __pbn__TableName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Stream : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream_id", IsRequired = true)]
        public string StreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"creation_time", IsRequired = true)]
        public long CreationTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListStreamResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"streams")]
        public global::System.Collections.Generic.List<Stream> Streams { get; } = new global::System.Collections.Generic.List<Stream>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamShard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shard_id", IsRequired = true)]
        public string ShardId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"parent_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ParentId
        {
            get { return __pbn__ParentId ?? ""; }
            set { __pbn__ParentId = value; }
        }
        public bool ShouldSerializeParentId() => __pbn__ParentId != null;
        public void ResetParentId() => __pbn__ParentId = null;
        private string __pbn__ParentId;

        [global::ProtoBuf.ProtoMember(3, Name = @"parent_sibling_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ParentSiblingId
        {
            get { return __pbn__ParentSiblingId ?? ""; }
            set { __pbn__ParentSiblingId = value; }
        }
        public bool ShouldSerializeParentSiblingId() => __pbn__ParentSiblingId != null;
        public void ResetParentSiblingId() => __pbn__ParentSiblingId = null;
        private string __pbn__ParentSiblingId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DescribeStreamRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream_id", IsRequired = true)]
        public string StreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"inclusive_start_shard_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InclusiveStartShardId
        {
            get { return __pbn__InclusiveStartShardId ?? ""; }
            set { __pbn__InclusiveStartShardId = value; }
        }
        public bool ShouldSerializeInclusiveStartShardId() => __pbn__InclusiveStartShardId != null;
        public void ResetInclusiveStartShardId() => __pbn__InclusiveStartShardId = null;
        private string __pbn__InclusiveStartShardId;

        [global::ProtoBuf.ProtoMember(3, Name = @"shard_limit")]
        public int ShardLimit
        {
            get { return __pbn__ShardLimit.GetValueOrDefault(); }
            set { __pbn__ShardLimit = value; }
        }
        public bool ShouldSerializeShardLimit() => __pbn__ShardLimit != null;
        public void ResetShardLimit() => __pbn__ShardLimit = null;
        private int? __pbn__ShardLimit;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DescribeStreamResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream_id", IsRequired = true)]
        public string StreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"expiration_time", IsRequired = true)]
        public int ExpirationTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"creation_time", IsRequired = true)]
        public long CreationTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"stream_status", IsRequired = true)]
        public StreamStatus StreamStatus { get; set; } = StreamStatus.StreamEnabling;

        [global::ProtoBuf.ProtoMember(6, Name = @"shards")]
        public global::System.Collections.Generic.List<StreamShard> Shards { get; } = new global::System.Collections.Generic.List<StreamShard>();

        [global::ProtoBuf.ProtoMember(7, Name = @"next_shard_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NextShardId
        {
            get { return __pbn__NextShardId ?? ""; }
            set { __pbn__NextShardId = value; }
        }
        public bool ShouldSerializeNextShardId() => __pbn__NextShardId != null;
        public void ResetNextShardId() => __pbn__NextShardId = null;
        private string __pbn__NextShardId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetShardIteratorRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream_id", IsRequired = true)]
        public string StreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"shard_id", IsRequired = true)]
        public string ShardId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp")]
        public long Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp() => __pbn__Timestamp != null;
        public void ResetTimestamp() => __pbn__Timestamp = null;
        private long? __pbn__Timestamp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetShardIteratorResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shard_iterator", IsRequired = true)]
        public string ShardIterator { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamRecordRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shard_iterator", IsRequired = true)]
        public string ShardIterator { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"limit")]
        public int Limit
        {
            get { return __pbn__Limit.GetValueOrDefault(); }
            set { __pbn__Limit = value; }
        }
        public bool ShouldSerializeLimit() => __pbn__Limit != null;
        public void ResetLimit() => __pbn__Limit = null;
        private int? __pbn__Limit;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStreamRecordResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream_records")]
        public global::System.Collections.Generic.List<StreamRecord> StreamRecords { get; } = new global::System.Collections.Generic.List<StreamRecord>();

        [global::ProtoBuf.ProtoMember(2, Name = @"next_shard_iterator")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NextShardIterator
        {
            get { return __pbn__NextShardIterator ?? ""; }
            set { __pbn__NextShardIterator = value; }
        }
        public bool ShouldSerializeNextShardIterator() => __pbn__NextShardIterator != null;
        public void ResetNextShardIterator() => __pbn__NextShardIterator = null;
        private string __pbn__NextShardIterator;

        [global::ProtoBuf.ProtoContract()]
        public partial class StreamRecord : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"action_type", IsRequired = true)]
            public ActionType ActionType { get; set; } = ActionType.PutRow;

            [global::ProtoBuf.ProtoMember(2, Name = @"record", IsRequired = true)]
            public byte[] Record { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ComputeSplitPointsBySizeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_name", IsRequired = true)]
        public string TableName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"split_size", IsRequired = true)]
        public long SplitSize { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ComputeSplitPointsBySizeResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"consumed", IsRequired = true)]
        public ConsumedCapacity Consumed { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"schema")]
        public global::System.Collections.Generic.List<PrimaryKeySchema> Schemas { get; } = new global::System.Collections.Generic.List<PrimaryKeySchema>();

        [global::ProtoBuf.ProtoMember(3, Name = @"split_points")]
        public global::System.Collections.Generic.List<byte[]> SplitPoints { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(4, Name = @"locations")]
        public global::System.Collections.Generic.List<SplitLocation> Locations { get; } = new global::System.Collections.Generic.List<SplitLocation>();

        [global::ProtoBuf.ProtoContract()]
        public partial class SplitLocation : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"location", IsRequired = true)]
            public string Location { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"repeat", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
            public long Repeat { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum PrimaryKeyType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"INTEGER")]
        Integer = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"STRING")]
        String = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"BINARY")]
        Binary = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PrimaryKeyOption
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AUTO_INCREMENT")]
        AutoIncrement = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum BloomFilterType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CELL")]
        Cell = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ROW")]
        Row = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum TableStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ACTIVE")]
        Active = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"INACTIVE")]
        Inactive = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LOADING")]
        Loading = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"UNLOADING")]
        Unloading = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"UPDATING")]
        Updating = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RowExistenceExpectation
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IGNORE")]
        Ignore = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPECT_EXIST")]
        ExpectExist = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"EXPECT_NOT_EXIST")]
        ExpectNotExist = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReturnType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"RT_NONE")]
        RtNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RT_PK")]
        RtPk = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OperationType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PUT")]
        Put = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"UPDATE")]
        Update = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE")]
        Delete = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Direction
    {
        [global::ProtoBuf.ProtoEnum(Name = @"FORWARD")]
        Forward = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BACKWARD")]
        Backward = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum StreamStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"STREAM_ENABLING")]
        StreamEnabling = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"STREAM_ACTIVE")]
        StreamActive = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ActionType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PUT_ROW")]
        PutRow = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"UPDATE_ROW")]
        UpdateRow = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE_ROW")]
        DeleteRow = 3,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
