// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace com.alicloud.openservices.tablestore.core.protocol.sql.flatbuffers
{

    public enum DataType : sbyte
    {
        NONE = 0,
        LONG = 1,
        BOOLEAN = 2,
        DOUBLE = 3,
        STRING = 4,
        BINARY = 5,
        STRING_RLE = 6,
    };


}
